# Generated by Django 5.0.6 on 2024-07-04 04:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagementindexpage',
            old_name='intro',
            new_name='scope',
        ),
        migrations.AddField(
            model_name='engagementindexpage',
            name='target',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
