# Generated by Django 5.0.6 on 2024-07-06 08:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_applicationpage_networkpage'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField()),
                ('username', models.CharField(blank=True, max_length=128)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('credentials_retrieved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('target', wagtail.fields.RichTextField()),
                ('test_execution', models.DateTimeField()),
                ('expected_behavior', wagtail.fields.RichTextField()),
                ('real_behavior', wagtail.fields.RichTextField(blank=True)),
                ('test_status', models.CharField(choices=[('detected', 'Detected'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('successful', 'Successful')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='hostpage',
            name='hostname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='hostpage',
            name='operating_system',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='networkpage',
            name='ip_range',
            field=models.CharField(help_text='E. 192.168.1.0/24, 192.168.1.1-192.168.1.10', max_length=255),
        ),
    ]
